# Generated by Django 3.1.5 on 2021-01-23 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='schedule_date')),
                ('user_name', models.CharField(max_length=128, verbose_name='user_name')),
                ('schedule', models.CharField(max_length=128, verbose_name='schedule')),
                ('remark', models.TextField(verbose_name='remark')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='user_name')),
                ('mail_address', models.CharField(max_length=128, verbose_name='mail_address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
    ]
